version: '3.8'

services:
  hiddify:
    image: ghcr.io/hiddify/hiddify-next-core/cli:latest
    network_mode: host
    environment:
      CONFIG: "https://raw.githubusercontent.com/ircfspace/warpsub/main/export/warp#WARP%20(IRCF)"
    volumes:
      - ./hiddify.json:/hiddify/hiddify.json
    command: ["/opt/hiddify.sh"]
